version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.11.13-management
    container_name: rabbitmq
    hostname: rabbitmq
#    volumes:
#      - /var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - .env
  auth:
    build:
      context: ./
      dockerfile: ./apps/auth/Dockerfile
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev auth
  film:
    build:
      context: ./
      dockerfile: ./apps/film/Dockerfile
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev film

  person:
    build:
      context: ./
      dockerfile: ./apps/person/Dockerfile
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev person
  genre:
    build:
      context: ./
      dockerfile: ./apps/genre/Dockerfile
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev genre
  country:
    build:
      context: ./
      dockerfile: ./apps/country/Dockerfile
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev country
  occupation:
    build:
      context: ./
      dockerfile: ./apps/occupation/Dockerfile
    env_file:
      - .env

    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev occupation
  api:
    build:
      context: ./
      dockerfile: ./apps/api/Dockerfile
    ports:
      - '4000:5000'
    env_file:
      - .env
    depends_on:
#      - country
#      - occupation
      - postgres
      - rabbitmq
      - auth
#      - film
      - person
#      - genre

    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev api
  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./db/data:/var/lib/postgres/data
